### ISSUE TITLE
Unhandled load error 

### ISSUE THREAD

**Issue by Venny23437** [Lauriethefish/QuestPatcher#100]
QuestPatcher.Core.AdbException: error: device not found

   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 148
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 179
   at QuestPatcher.Core.AndroidDebugBridge.IsPackageInstalled(String packageId) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 208
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 113
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 91

**Comment by Lauriethefish** [comment]
This is an ADB issue, not a questpatcher bug. I suggest restarting both your device and QuestPatcher, and trying a different USB cable.
