### ISSUE TITLE
Unhandled Load Error

### ISSUE THREAD

**Issue by Phar27** [Lauriethefish/QuestPatcher#102]
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at QuestPatcher.Core.ProcessUtil.InvokeAndCaptureOutput(String fileName, String arguments) in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/ProcessUtil.cs:line 71
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/AndroidDebugBridge.cs:line 116
   at QuestPatcher.Core.AndroidDebugBridge.IsPackageInstalled(String packageId) in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/AndroidDebugBridge.cs:line 191
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/QuestPatcherService.cs:line 112
   at QuestPatcher.Services.QuestPatcherUIService.LoadAndHandleErrors() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher/Services/QuestPatcherUIService.cs:line 95

**Comment by Lauriethefish** [comment]
Does this happen consistently? I don't have a mac so it's difficult for me to debug.
