### ISSUE TITLE
Unhandled Load Error

### ISSUE THREAD

**Issue by XeniLos** [Lauriethefish/QuestPatcher#106]
_**Hello, I Launch QuestPatcher on Windows and have this Error**_

> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult )
   at System.Net.WebClient.GetWebResponse(WebRequest , IAsyncResult )
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest )
   at System.Net.WebClient.DownloadBitsAsync(WebRequest , Stream , AsyncOperation , Action`3 )
   at QuestPatcher.Core.ExternalFilesDownloader.DownloadFile(ExternalFileType fileType, FileInfo fileInfo, String downloadUrl, String saveLocation) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\ExternalFilesDownloader.cs:line 329
   at QuestPatcher.Core.ExternalFilesDownloader.GetFileLocation(ExternalFileType fileType) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\ExternalFilesDownloader.cs:line 419
   at QuestPatcher.Core.AndroidDebugBridge.PrepareAdbPath() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 93
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 109
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 181
   at QuestPatcher.Core.AndroidDebugBridge.IsPackageInstalled(String packageId) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 210
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 113
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 91

**Comment by Lauriethefish** [comment]
Please check that your internet connection is working properly. This is not a problem with QuestPatcher.
