### ISSUE TITLE
Patching error 

### ISSUE THREAD

**Issue by theJesterV2** [Lauriethefish/QuestPatcher#110]
I've been trying to patch gorilla tag for the past day and whenever I do it says this.

QuestPatcher.Core.AdbException: adb: error: failed to stat remote object '/sdcard/QuestPatcher/com.AnotherAxiom.GorillaTag/installedMods/PublicGravMonke/mod.json': No such file or directory

   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 148
   at QuestPatcher.Core.AndroidDebugBridge.DownloadFile(String name, String destination) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 185
   at QuestPatcher.Core.Modding.QModProvider.LoadLegacyMods() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\QModProvider.cs:line 282
   at QuestPatcher.Core.Modding.ModManager.LoadModsForCurrentApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\ModManager.cs:line 152
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 129
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 91

**Comment by Lauriethefish** [comment]
Go to SideQuest and delete the `/sdcard/QuestPatcher` directory, then try again.
