### ISSUE TITLE
mod downloading error

### ISSUE THREAD

**Issue by theJesterV2** [Lauriethefish/QuestPatcher#111]
I'm trying to download the gorilla tag mods and it gives me this error

QuestPatcher.Core.AdbException: cp: '/sdcard/Android/data/com.AnotherAxiom.GorillaTag/files/libs/libbeatsaber-hook_2_3_0.so' not directory

   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 148
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 180
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommands(List`1 commands) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 168
   at QuestPatcher.Core.AndroidDebugBridge.CopyFiles(List`1 paths) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 278
   at QuestPatcher.Core.Modding.QPMod.Install(List`1 installedInBranch) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\QPMod.cs:line 131
   at QuestPatcher.ViewModels.Modding.ModViewModel.InstallSafely() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\ViewModels\Modding\ModViewModel.cs:line 134

**Comment by Lauriethefish** [comment]
Gorilla tag mods aren't supported right now
