### ISSUE TITLE
Unhandled Load Error

### ISSUE THREAD

**Issue by ChanzDetsker** [Lauriethefish/QuestPatcher#132]
So my computer restarted in the middle of uninstalling some mods for beat saber and I now have this error. Is there any way to resolve.

**System.IO.IOException: The process cannot access the file 'C:\Users\15708\AppData\Roaming\QuestPatcher\tools\platform-tools\platform-tools\adb.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.SyncWindowsFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean )
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry , String , Boolean )
   at System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory(ZipArchiveEntry , String , Boolean )
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive , String , Boolean )
   at QuestPatcher.Core.ExternalFilesDownloader.<>c__DisplayClass32_0.<DownloadFile>b__0() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\ExternalFilesDownloader.cs:line 349
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object )
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
--- End of stack trace from previous location ---
   at QuestPatcher.Core.ExternalFilesDownloader.DownloadFile(ExternalFileType fileType, FileInfo fileInfo, String downloadUrl, String saveLocation) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\ExternalFilesDownloader.cs:line 335
   at QuestPatcher.Core.ExternalFilesDownloader.GetFileLocation(ExternalFileType fileType) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\ExternalFilesDownloader.cs:line 419
   at QuestPatcher.Core.AndroidDebugBridge.PrepareAdbPath() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 93
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 109
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 181
   at QuestPatcher.Core.AndroidDebugBridge.IsPackageInstalled(String packageId) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 210
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 113
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 91**

**Comment by Lauriethefish** [comment]
I suggest running `taskkill /IM adb.exe` in command prompt and then opening QuestPatcher again.
