### ISSUE TITLE
Unhandled Load Error

### ISSUE THREAD

**Issue by AshelinSama** [Lauriethefish/QuestPatcher#139]
I just freshly installed QuestPatcher and am using Meta Quest 3. I tried both the "QuestPatcher-windows.exe" as well as the standalone. I am immediately met with the following error as soon as I open QuestPatcher:

![UnhandledLoaderror](https://github.com/Lauriethefish/QuestPatcher/assets/125989209/9c39d657-7a31-44fb-bd7e-706adfd7f29e)
```
QuestPatcher.Core.AdbException
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 298
   at QuestPatcher.Core.AndroidDebugBridge.DownloadFile(String name, String destination) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 336
   at QuestPatcher.Core.AndroidDebugBridge.DownloadApk(String packageId, String destination) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 350
   at QuestPatcher.Core.InstallManager.LoadInstalledApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 137
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 132
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 96
```

If I click "Change App", it gives me the "Device offline" error even after restarting both my PC and my Quest 3. SideQuest correctly detects and can connect with my Quest 3 at this same time.

![offline](https://github.com/Lauriethefish/QuestPatcher/assets/125989209/c3ebf96d-ede1-4d9f-ab47-fb145c0fdff8)

**Comment by AshelinSama** [comment]
Managed to resolve the issue by using a different USB port. It seems the USB port I was using kept intermittently disconnecting the Quest, and that was causing the issue.
