### ISSUE TITLE
Quand use questpatcher with my quest 3

### ISSUE THREAD

**Issue by Ozenz25** [Lauriethefish/QuestPatcher#142]
Hello,

When I try to use questpatcher I have this message : 
Can you help me please ? 

QuestPatcher.Core.AdbException
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 298
   at QuestPatcher.Core.AndroidDebugBridge.DownloadFile(String name, String destination) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 336
   at QuestPatcher.Core.AndroidDebugBridge.DownloadApk(String packageId, String destination) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 350
   at QuestPatcher.Core.InstallManager.LoadInstalledApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 137
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 132
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 96

**Comment by Lauriethefish** [comment]
It seems as though ADB is returning a faulty error code. Try restarting your PC and Quest and if that doesn't work, delete the files in `%appdata%/QuestPatcher`.

**Comment by Lauriethefish** [comment]
Since this is a problem relating to ADB: it is failing to access your Quest, I will close this issue as I can't do much about it.

**Comment by callanbruh** [comment]
has anyone found the solution to this issue yet?
