### ISSUE TITLE
error when running quest patcher.app on macos

### ISSUE THREAD

**Issue by smetjen** [Lauriethefish/QuestPatcher#147]
when running the Quest Patcher.app  on MacBook Pro on Mac OS Sonoma I receive below critical error messages

I'm not really an expert, just trying to mod beat saber on my meta quest 3 :-)

System.UnauthorizedAccessException: Access to the path '/Users/tsmetjen/.config/QuestPatcher' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at QuestPatcher.Core.SpecialFolders.CreateAndDeleteTemp() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/SpecialFolders.cs:line 62
   at QuestPatcher.Core.QuestPatcherService..ctor(IUserPrompter prompter) in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/QuestPatcherService.cs:line 44
   at QuestPatcher.Services.QuestPatcherUiService..ctor(IClassicDesktopStyleApplicationLifetime appLifetime) in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher/Services/QuestPatcherUiService.cs:line 37
   at QuestPatcher.App.OnFrameworkInitializationCompleted() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher/App.axaml.cs:line 77

**Comment by Lauriethefish** [comment]
Try opening a terminal and running `sudo chown -R <username> .config` replace `<username>` with your username (you can get this by running `whoami`).

Basically the permissions for your home folder are messed up so QP can't access it.

**Comment by smetjen** [comment]
HiThx for the help. I tried but got message ‘.config: Permission denied….operation not permitted’GrtzJürgenVerstuurd vanaf mijn iPhoneOp 18 feb 2024 om 07:41 heeft Lauriethefish ***@***.***> het volgende geschreven:﻿
Try opening a terminal and running sudo chown -R <username> .config replace <username> with your username (you can get this by running whoami).
Basically the permissions for your home folder are messed up so QP can't access it.

**Comment by Lauriethefish** [comment]
It seems like your user doesn't have the permissions to update the necessary attributes. Make sure that you're an administrator.

**Comment by Lauriethefish** [comment]
Closing as no further reports of the issue, seems like an isolated case of user permissions being set wrongly.
