### ISSUE TITLE
Quest Patcher Unhandled Load Error

### ISSUE THREAD

**Issue by TryptaX** [Lauriethefish/QuestPatcher#155]
I get this error with the every versions of the quest patcher. Please help.

QuestPatcher.Core.Patching.PatchingException: The loaded APK did not contain a 32 or 64 bit libil2cpp for patching. This either means that it is of an unsupported architecture, or it is not an il2cpp unity app. Please complain to Laurie if you're annoyed that QuestPatcher doesn't support unreal.
   at QuestPatcher.Core.InstallManager.CheckModdingStatus() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 157
   at QuestPatcher.Core.InstallManager.CheckModdingStatus() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 162
   at QuestPatcher.Core.InstallManager.LoadInstalledApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 139
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 132
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 96

**Comment by qe201020335** [comment]
Which game were you trying to patch

**Comment by reallycoo1** [comment]
Now I'm having this error - I'm trying to mod beatsaber? This is so stressful.

**Comment by Lauriethefish** [comment]
Are you absolutely sure it's the same error? I.e. the one containing "did not contain a 32 bit or 64 bit libil2cpp for patching".
This error shouldn't be possible with Beat Saber, but it's possible you're getting some other, unrelated error.
