### ISSUE TITLE
Unhandled Load Error

### ISSUE THREAD

**Issue by Flicktional** [Lauriethefish/QuestPatcher#156]
Launching the app and trying to connect my headset receives this error message

QuestPatcher.Core.Patching.PatchingException: The loaded APK did not contain a 32 or 64 bit libil2cpp for patching. This either means that it is of an unsupported architecture, or it is not an il2cpp unity app. Please complain to Laurie if you're annoyed that QuestPatcher doesn't support unreal.
   at QuestPatcher.Core.InstallManager.CheckModdingStatus() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 166
   at QuestPatcher.Core.InstallManager.LoadInstalledApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 139
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 131
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 94

**Comment by qe201020335** [comment]
Duplicated issue. See #155
