### ISSUE TITLE
Detect `DELETE_FAILED_INTERNAL_ERROR` and continue patching after uninstall

### ISSUE THREAD

**Issue by Jkey1410** [Lauriethefish/QuestPatcher#169]
Patching failed!: QuestPatcher.Core.AdbException: Failure [DELETE_FAILED_INTERNAL_ERROR]

   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 148
   at QuestPatcher.Core.AndroidDebugBridge.UninstallApp(String packageId) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 186
   at QuestPatcher.Core.Patching.PatchingManager.PatchApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Patching\PatchingManager.cs:line 463
   at QuestPatcher.ViewModels.PatchingViewModel.StartPatching() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\ViewModels\PatchingViewModel.cs:line 59

**Comment by Lauriethefish** [comment]
This shows that the APK was already uninstalled by the time QuestPatcher tried to uninstall it to prepare for installing the patched version.

Any ideas what might be doing this on your Quest?

I will change this issue into a request to detect this error and not fail patching, since it isn't technically something that should halt the patching process.
