### ISSUE TITLE
Kubuntu unhandled load error on startup

### ISSUE THREAD

**Issue by PotHoe** [Lauriethefish/QuestPatcher#172]
This 
```
System.InvalidOperationException: Cannot process request because the process (129916) has exited.
   at System.Diagnostics.Process.ThrowIfExited(Boolean )
   at System.Diagnostics.Process.EnsureState(State )
   at System.Diagnostics.Process.get_Modules()
   at System.Diagnostics.Process.get_MainModule()
   at QuestPatcher.Core.ProcessUtil.InvokeAndCaptureOutput(String fileName, String arguments) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\ProcessUtil.cs:line 79
   at QuestPatcher.Core.AndroidDebugBridge.SetAdbPathIfValid(String adbExecutablePath) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 169
   at QuestPatcher.Core.AndroidDebugBridge.PrepareAdbPath() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 135
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 376
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 466
   at QuestPatcher.Core.AndroidDebugBridge.IsPackageInstalled(String packageId) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 495
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 117
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 96
``` 
...comes up every time I start quest patcher using the ubuntu version. I use kubuntu.

**Comment by qe201020335** [comment]
Can you try run adb from terminal and see if it is working by itself?

**Comment by Lauriethefish** [comment]
I'll make an attempt to debug this issue with a VM at some point.

**Comment by Lauriethefish** [comment]
In de7e817fdef6abee04376d9b20b5bf3071511eee , this failure was changed to a warning as it is not successful that the call succeeds in order for QuestPatcher to use ADB.

This should fix the issue 👍🏼

**Comment by Lauriethefish** [comment]
Sorry, proper fix now implemented.
Will come out with next update.
