### ISSUE TITLE
Kill adb client instances upon shutdown

### ISSUE THREAD

**Issue by AiToolsdownload** [Lauriethefish/QuestPatcher#181]
![Screenshot 2024-05-14 175759](https://github.com/Lauriethefish/QuestPatcher/assets/161177863/32fd99ed-ee02-46e2-a2a4-c9164992adef)

**Comment by qe201020335** [comment]
Can you copy and post the entire exception here?

**Comment by AiToolsdownload** [comment]
> Can you copy and post the entire exception here?

QuestPatcher.Core.AdbException: Code 1: adb: error: cannot write 'C:\Users\Malaj\AppData\Local\Temp\QuestPatcher\patching\currentlyInstalled.apk': Input/output error
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 433
   at QuestPatcher.Core.AndroidDebugBridge.DownloadFile(String name, String destination) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 471
   at QuestPatcher.Core.AndroidDebugBridge.DownloadApk(String packageId, String destination) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 485
   at QuestPatcher.Core.InstallManager.LoadInstalledApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 143
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 132
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 96

**Comment by callanbruh** [comment]
yo I have the same issue. Did you ever figure this out?

**Comment by Lauriethefish** [comment]
This issue is caused by you previously already having a QuestPatcher instance open that's writing to `currentlyInstalled.apk`. When this is closed, ADB continues writing to the APK in the background.

Changing this issue to be a request to properly kill any adb *client* (not daemon) instances upon shutdown.
