### ISSUE TITLE
im getting some critical error when i try to start it

### ISSUE THREAD

**Issue by cloudy-gameDev** [Lauriethefish/QuestPatcher#182]
![Screenshot 2024-05-24 001721](https://github.com/Lauriethefish/QuestPatcher/assets/67645763/b4caa4be-437c-448c-a62d-19232495eeb1)
 

full code thing: System.IO.IOException: The process cannot access the file 'currentlyInstalled.apk' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String , WIN32_FIND_DATA& , Boolean )
   at System.IO.FileSystem.RemoveDirectory(String , Boolean )
   at System.IO.Directory.Delete(String , Boolean )
   at QuestPatcher.Core.SpecialFolders.CreateAndDeleteTemp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\SpecialFolders.cs:line 69
   at QuestPatcher.Core.QuestPatcherService..ctor(IUserPrompter prompter) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 44
   at QuestPatcher.Services.QuestPatcherUiService..ctor(IClassicDesktopStyleApplicationLifetime appLifetime) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 37
   at QuestPatcher.App.OnFrameworkInitializationCompleted() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\App.axaml.cs:line 77

**Comment by Lauriethefish** [comment]
You already have another instance of QuestPatcher open in the background. Restarting your PC will fix this issue.
