### ISSUE TITLE
"Unhandled Load Error" trying to patch fresh Beat Saber install

### ISSUE THREAD

**Issue by BoyyLadd** [Lauriethefish/QuestPatcher#183]
Here's the full error message I get every time i try patching: 
QuestPatcher.Core.AdbException: Code 1: [  0%] /data/app/~~RH34mbZGhkad6ZMZjvfNUA==/com.beatgames.beatsaber-EjpzZC78bKB3-C9tpvJLZw==/base.apk
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 433
   at QuestPatcher.Core.AndroidDebugBridge.DownloadFile(String name, String destination) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 471
   at QuestPatcher.Core.AndroidDebugBridge.DownloadApk(String packageId, String destination) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 485
   at QuestPatcher.Core.InstallManager.LoadInstalledApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 143
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 132
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 96

I run QuestPatcher as administrator, and it begins trying to download the apk. after a while, this message pops up and I don't know what to do about it.

**Comment by BoyyLadd** [comment]
Problem solved. No one ever told me this in any of the videos I watched, but you'll need to download "adb tools" to do this. here's the video I followed: https://www.youtube.com/watch?v=zfMkeni1z-Q&ab_channel=TechnoCraze.
