### ISSUE TITLE
Operation not permitted issue

### ISSUE THREAD

**Issue by IuriiChe** [Lauriethefish/QuestPatcher#184]
I have this issue:
QuestPatcher.Core.AdbException: Code 1: rm: chmod '/sdcard/Android/data/com.beatgames.beatsaber/files/mods/' to 0700: Operation not permitted
rm: /sdcard/Android/data/com.beatgames.beatsaber/files/mods/: Permission denied
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 433
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 466
   at QuestPatcher.Core.AndroidDebugBridge.RemoveDirectory(String path) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 570
   at QuestPatcher.Core.Modding.ModManager.CreateModDirectories() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\ModManager.cs:line 189
   at QuestPatcher.Core.Modding.ModManager.LoadModsForCurrentApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\ModManager.cs:line 210
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 137
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 96

I am not sure if it is related, but to get access to the required folder I need this address: This PC\Quest 3\Internal shared storage\Android\data\com.beatgames.beatsaber\files  
Is it possible to tell Quest patcher to look in another folder?

**Comment by Lauriethefish** [comment]
OK, so breaking down this issue:
- QuestPatcher is attempting to delete the `/sdcard/Android/data/com.beatgames.beatsaber/files/mods/` directory in order to recreate it.
- It's doing this because it's detected that permissions on that folder are messed up and it can't fix them as Android is denying it permission.
- But... Android is denying it permission to recreate the folder too, so now it's stuck.

This isn't something QP can directly fix - the measures taken above are already my best attempt at a fix in both cases.
If the directories are truly this messed up, your best option is to reinstall the app you're modding.

Perhaps in the future I could suggest to the user to reinstall the app in this case. I'll change this issue accordingly.
