### ISSUE TITLE
Patching failed

### ISSUE THREAD

**Issue by wjoseph0** [Lauriethefish/QuestPatcher#19]
I am encountering an issue with patching Gorilla Tag. Here is the log:
```
Copying APK to patched location . . .
Copying files to patch APK . . .
Checking index for unstripped libunity.so . . .
Unstripped libunity found. Downloading . . .
Copying libmain.so and libmodloader.so . . .
Patching manifest . . .
Loading manifest as AXML . . .
Adding permission android.permission.READ_EXTERNAL_STORAGE
Adding permission android.permission.WRITE_EXTERNAL_STORAGE
Adding permission android.permission.MANAGE_EXTERNAL_STORAGE
Adding debuggable flag . . .
Adding legacy external storage flag . . .
Saving manifest as AXML . . .
Adding tag . . .
Closing APK archive . . .
Signing APK (this might take a while) . . .
Signing the APK failed with zipalign enabled. Falling back to non-zipalign . . .
Patching failed!: QuestPatcher.Core.SigningException: Signed APK at C:\Users\Jack Wagner\AppData\Local\Temp\QuestPatcher\patching\patched-debugSigned.apk was missing, signing must have failed
   at QuestPatcher.Core.ApkTools.SignApk(String apkPath, Boolean useZipAlign)
   at QuestPatcher.Core.Patching.PatchingManager.PatchApp()
   at QuestPatcher.ViewModels.PatchingViewModel.StartPatching()
```

**Comment by Lauriethefish** [comment]
Please provide a full log by pressing open logs folder and uploading the file called `log.log` or just `log` here.

**Comment by wjoseph0** [comment]
[log.log](https://github.com/Lauriethefish/QuestPatcher/files/6797395/log.log)

**Comment by Lauriethefish** [comment]
Alright, nice.
