### ISSUE TITLE
Unhandled Load Error

### ISSUE THREAD

**Issue by Griffen145** [Lauriethefish/QuestPatcher#194]
I just installed QuestPatcher on Windows 11 and am using Meta Quest 3. I tried both the "QuestPatcher-windows.exe" as well as the standalone. But I kept getting the same error message after installing and reinstalling: 
![Screenshot 2024-08-11 234225](https://github.com/user-attachments/assets/71e6b29f-6c3f-4314-b425-a60b71e54a86)

QuestPatcher.Core.Patching.PatchingException: The loaded APK did not contain a 32 or 64 bit libil2cpp for patching. This either means that it is of an unsupported architecture, or it is not an il2cpp unity app. Please complain to Laurie if you're annoyed that QuestPatcher doesn't support unreal.
   at QuestPatcher.Core.InstallManager.CheckModdingStatus() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 163
   at QuestPatcher.Core.InstallManager.CheckModdingStatus() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 168
   at QuestPatcher.Core.InstallManager.LoadInstalledApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\InstallManager.cs:line 145
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 132
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 110

**Comment by Lauriethefish** [comment]
The app you're trying to mod isn't an il2cpp unity app, so QuestPatcher can't mod it.
You need to pick an app which is il2cpp unity (an example would be Beat Saber).
