### ISSUE TITLE
Patching failed from QuestLoader to Scotland2

### ISSUE THREAD

**Issue by Math192800** [Lauriethefish/QuestPatcher#197]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetsTools.NET.Extra.AssetHelper.FindAssetClassByID(ClassDatabaseFile cldb, UInt32 id)
   at AssetsTools.NET.Extra.AssetsManager.GetTemplateBaseField(AssetsFile file, AssetFileInfoEx info, Boolean forceFromCldb)
   at AssetsTools.NET.Extra.AssetsManager.GetTypeInstance(AssetsFile file, AssetFileInfoEx info, Boolean forceFromCldb)
   at AssetsTools.NET.Extra.AssetsManager.GetTypeInstance(AssetsFileInstance inst, AssetFileInfoEx info, Boolean forceFromCldb)
   at QuestPatcher.Core.Patching.PatchingManager.AddFlatscreenSupport(ApkZip apk, String ovrPlatformSdkPath) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Patching\PatchingManager.cs:line 433
   at QuestPatcher.Core.Patching.PatchingManager.ModifyApk(String mainPath, String modloaderPath, String unityPath, String ovrPlatformSdkPath, String libsDirectory, ApkZip apk) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Patching\PatchingManager.cs:line 490
   at QuestPatcher.Core.Patching.PatchingManager.PatchApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Patching\PatchingManager.cs:line 668
   at QuestPatcher.Core.Patching.PatchingManager.PatchApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Patching\PatchingManager.cs:line 675
   at QuestPatcher.ViewModels.PatchingViewModel.StartPatching() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\ViewModels\PatchingViewModel.cs:line 62



Uploading scotland2 to the quest
Checking index for unstripped libunity.so . . .
Unstripped libunity found. Downloading . . .
Copying APK to temporary location . . .
Copying files to patch the apk . . .
Copying libmain.so and libmodloader.so . . .
Adding unstripped libunity.so . . .
Adding flatscreen support . . .
Patching failed!
```

Tried and restart and reinstall and nothing works.

**Comment by qe201020335** [comment]
Is the `AddFlatscreenSupport` intended?

**Comment by Lauriethefish** [comment]
^ This won't work on most newer versions of Beat Saber, only older versions.

**Comment by Math192800** [comment]
work great on 1.28 whit QuestLoader. i have the 1.37 version instaled whit QuestAppVersionSwitcher, this apk say the 1.37 is the last version we can mods. after looking on ghithub, i see the 1.28 version works whit QuestLoader so i switch for the older version
