### ISSUE TITLE
Cannot delete cosmetics with an apostrophe in file name due to unescaped quote.

### ISSUE THREAD

**Issue by Voxed1** [Lauriethefish/QuestPatcher#31]
File I have attempted to delete: `Rick's hair.hat`

```
QuestPatcher.Core.AdbException: /system/bin/sh: no closing quote

   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 148
   at QuestPatcher.Core.AndroidDebugBridge.RemoveFile(String path) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 231
   at QuestPatcher.Core.Modding.FileCopyType.RemoveFile(String name) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\FileCopyType.cs:line 139
   at QuestPatcher.ViewModels.OtherItemsViewModel.DeleteFiles(String[] filePaths) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\ViewModels\OtherItemsViewModel.cs:line 133
```

**Comment by Lauriethefish** [comment]
I am aware of this issue. I already escape quotes twice so it's a bit of a pain to fix, but I can properly fix next update when I move to an ADB library instead of manual ADB manipulation.

**Comment by mcwindex** [comment]
hi i am having the same issue. do you know how to fix this?

**Comment by Lauriethefish** [comment]
Delete the file using SideQuest

**Comment by MicroCBer** [comment]
Can this be fixed by using an escape library that auto turns the file name&path into the right format? I remember the last time I fixed a similar problem by doing this.

**Comment by memeruler2** [comment]
I am still having this problem and have had it for a while, im very confused on how to delete it using sidequest, please help me.
