### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by omnom143** [Lauriethefish/QuestPatcher#39]
It works fine on sidequest

QuestPatcher.Core.AdbException: error: device '(null)' not found

   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 148
   at QuestPatcher.Core.AndroidDebugBridge.IsPackageInstalled(String packageId) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 191
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 112
   at QuestPatcher.Services.QuestPatcherUIService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUIService.cs:line 95

**Comment by Lauriethefish** [comment]
This is an ADB problem, not a QuestPatcher problem. You need to check your ADB drivers and developer mode.
