### ISSUE TITLE
Patching failed: an unhandled error ocurred while attempting to patch the game

### ISSUE THREAD

**Issue by untitled5am** [Lauriethefish/QuestPatcher#70]
log:
QuestPatcher.Core.SigningException: Signed APK at C:\Users\johna\AppData\Local\Temp\QuestPatcher\patching\patched-debugSigned.apk was missing, signing must have failed
   at QuestPatcher.Core.ApkTools.SignApk(String apkPath, Boolean useZipAlign) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\ApkTools.cs:line 119
   at QuestPatcher.Core.Patching.PatchingManager.PatchApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Patching\PatchingManager.cs:line 431
   at QuestPatcher.ViewModels.PatchingViewModel.StartPatching() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\ViewModels\PatchingViewModel.cs:line 59

full log.log
[log.log](https://github.com/Lauriethefish/QuestPatcher/files/8488611/log.log)

**Comment by untitled5am** [comment]
@Lauriethefish

**Comment by Lauriethefish** [comment]
Update QuestPatcher

**Comment by untitled5am** [comment]
thanks

**Comment by untitled5am** [comment]
@Lauriethefish how do i update it

**Comment by Lauriethefish** [comment]
Please stop pinging me. Just download the new version and install it.
