### ISSUE TITLE
QuestPatcher.Core.AdbException: Failure

### ISSUE THREAD

**Issue by Bennofant0** [Lauriethefish/QuestPatcher#87]
Hi,
I get this error message all the time when I try to patch:

QuestPatcher.Core.AdbException: Failure [DELETE_FAILED_INTERNAL_ERROR]

   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 148
   at QuestPatcher.Core.AndroidDebugBridge.UninstallApp(String packageId) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 186
   at QuestPatcher.Core.Patching.PatchingManager.PatchApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Patching\PatchingManager.cs:line 482
   at QuestPatcher.ViewModels.PatchingViewModel.StartPatching() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\ViewModels\PatchingViewModel.cs:line 59

Can anyone help?
Many thanks!
benni

**Comment by Lauriethefish** [comment]
This is unfortunately an ADB issue, so there isn't much I can do about it. Try the `Quick Fix` button in the `Tools & Options` tab.  You could try a factory reset of your Quest if nothing else works.
