### ISSUE TITLE
WTF?

### ISSUE THREAD

**Issue by bingbong233** [Lauriethefish/QuestPatcher#94]
QuestPatcher.Core.AdbException: cp: '/sdcard/Android/data/com.AnotherAxiom.GorillaTag/files/libs/libbeatsaber-hook_2_3_0.so' not directory

   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 148
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 180
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommands(List`1 commands) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 168
   at QuestPatcher.Core.AndroidDebugBridge.CopyFiles(List`1 paths) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 278
   at QuestPatcher.Core.Modding.QPMod.Install(List`1 installedInBranch) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\QPMod.cs:line 131
   at QuestPatcher.Core.Modding.QPMod.PrepareDependency(Dependency dependency, List`1 installedInBranch) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\QPMod.cs:line 282
   at QuestPatcher.Core.Modding.QPMod.Install(List`1 installedInBranch) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\QPMod.cs:line 94
   at QuestPatcher.ViewModels.Modding.ModViewModel.InstallSafely() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\ViewModels\Modding\ModViewModel.cs:line 140 dafuq?
![image](https://user-images.githubusercontent.com/115507752/194957370-704052af-cf78-48ab-85ea-36295fd12ea8.png)

**Comment by Lauriethefish** [comment]
Restarting questpatcher fixes this issue. For whatever reason, sometimes these directories don't get created right. I can't reproduce it.
